version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma-mizfa
    volumes:
      - .:/usr/src/app
      - uptime-kuma:/app/data
    ports:
      - "3002:3001"  # <Host Port>:<Container Port>
    restart: always

volumes:
  uptime-kuma:

